import americano from "./images/photos/Американо";
import capuccino from "./images/photos/Капучино";
import bagrovyi_zakat from "./images/photos/Багровый закат";
import brauni from "./images/photos/Брауни";
import gintonik from "./images/photos/Джин Тоник";
import domashniy_pirog from "./images/photos/Домашний пирог";
import greentea from "./images/photos/Зеленый чай";
import kruassan from "./images/photos/Круасаны";
import latte from "./images/photos/Латте";
import machiato from "./images/photos/Махиато";
import mohito from "./images/photos/Мохито";
import beer from "./images/photos/Пиво с вином";
import san_sebastian from "./images/photos/Сан-себастьян";
import teramisu from "./images/photos/Терамису";
import tort from "./images/photos/Торт";
import teawithmilk from "./images/photos/Чай с молоком";
import blacktea from "./images/photos/Черный чай";
import cheesecake from "./images/photos/Чизкейк";
import espresso from "./images/photos/Эспрессо";
import applepirog from "./images/photos/Яблочный пирог";

export const initialItems = [
  {
    id: 1,
    name: "Американо",
    price: "199",
    category: "Кофе",
    image: americano,
    description:
      "Америка́но — способ приготовления кофе, заключающийся в соединении определённого количества горячей воды и эспрессо.",
    ingredients: [
      { name: "Свежемолотый кофе", amount: 18, unit: "г" },
      { name: "Горячая вода", amount: 120, unit: "мл" },
    ],
  },
  {
    id: 2,
    name: "Капучино",
    price: "200",
    category: "Кофе",
    image: capuccino,
    description:
      "Капучи́но — кофейный напиток итальянской кухни на основе эспрессо с добавлением в него подогретого вспененного молока.",
    ingredients: [
      { name: "Свежемолотый кофе", amount: 18, unit: "г" },
      { name: "Молоко", amount: 150, unit: "мл" },
    ],
  },
  {
    id: 3,
    name: "Латте",
    price: "140",
    category: "Кофе",
    image: latte,
    description:
      "Ла́тте — кофейный напиток на основе молока, представляющий собой трёхслойную смесь из молочной пены, молока и кофе эспрессо.",
    ingredients: [
      { name: "Свежемолотый кофе", amount: 18, unit: "г" },
      { name: "Молоко", amount: 200, unit: "мл" },
    ],
  },
  {
    id: 4,
    name: "Макиато",
    price: "250",
    category: "Кофе",
    image: machiato,
    description:
      "Макиато — кофейный напиток, изготавливаемый путём добавления к эспрессо минимального количества молока, обычно взбитого.",
    ingredients: [
      { name: "Свежемолотый кофе", amount: 18, unit: "г" },
      { name: "Молоко", amount: 10, unit: "мл" },
    ],
  },
  {
    id: 5,
    name: "Эспрессо",
    price: "250",
    category: "Кофе",
    image: espresso,
    description:
      "Эспре́ссо — метод приготовления кофе путём прохождения горячей воды под давлением через фильтр с молотым кофе.",
    ingredients: [
      { name: "Свежемолотый кофе", amount: 18, unit: "г" },
      { name: "Горячая вода", amount: 30, unit: "мл" },
    ],
  },
  {
    id: 6,
    name: "Тирамису",
    price: "149",
    category: "Десерты",
    image: teramisu,
    description:
      "Слоеный десерт с кремом маскарпоне, пропитанный эспрессо и покрытый какао.",
    ingredients: [
      { name: "Маскарпоне", amount: 250, unit: "г" },
      { name: "Эспрессо", amount: 100, unit: "мл" },
      { name: "Яйца", amount: 3, unit: "шт" },
      { name: "Сахар", amount: 75, unit: "г" },
      { name: "Печенье Савоярди", amount: 200, unit: "г" },
      { name: "Какао для посыпки", amount: 20, unit: "г" },
    ],
  },
  {
    id: 7,
    name: "Чизкейк",
    price: "170",
    category: "Десерты",
    image: cheesecake,
    description:
      "Нежный сырный десерт на основе печенья с фруктовым топпингом.",
    ingredients: [
      { name: "Сливочный сыр", amount: 200, unit: "г" },
      { name: "Сахар", amount: 100, unit: "г" },
      { name: "Печенье для основы", amount: 200, unit: "г" },
      { name: "Сливочное масло", amount: 50, unit: "г" },
      { name: "Ягодный топпинг", amount: 100, unit: "г" },
    ],
  },
  {
    id: 8,
    name: "Брауни",
    price: "125",
    category: "Десерты",
    image: brauni,
    description:
      "Бра́уни — шоколадное пирожное коричневого цвета, прямоугольные куски нарезанного шоколадного пирога.",
    ingredients: [
      { name: "Черный шоколад", amount: 200, unit: "г" },
      { name: "Сахар", amount: 150, unit: "г" },
      { name: "Сливочное масло", amount: 100, unit: "г" },
      { name: "Яйца", amount: 3, unit: "шт" },
      { name: "Мука", amount: 100, unit: "г" },
      { name: "Грецкие орехи", amount: 50, unit: "г" },
    ],
  },
  {
    id: 9,
    name: "Панакота",
    price: "99",
    category: "Десерты",
    image: tort,
    description: "Итальянский десерт на основе сливок, сахара и желатина.",
    ingredients: [
      { name: "Сливки", amount: 500, unit: "мл" },
      { name: "Сахар", amount: 100, unit: "г" },
      { name: "Желатин", amount: 5, unit: "г" },
      { name: "Ванильный экстракт", amount: 5, unit: "мл" },
      { name: "Фруктовый соус", amount: 100, unit: "мл" },
    ],
  },
  {
    id: 10,
    name: "Сан-Себастьян",
    price: "400",
    category: "Десерты",
    image: san_sebastian,
    description:
      "В «Сан-Себастьяне» сердцевина остаётся кремовой, твердеет он только по краям. Так получается, потому что его выпекают при высокой температуре — 250 градусах — в течение 20 минут.",
    ingredients: [
      { name: "Сливочный сыр", amount: 500, unit: "г" },
      { name: "Сахар", amount: 200, unit: "г" },
      { name: "Яйца", amount: 4, unit: "шт" },
      { name: "Сливки", amount: 200, unit: "мл" },
      { name: "Мука", amount: 30, unit: "г" },
    ],
  },
  {
    id: 11,
    name: "Круассан",
    price: "160",
    category: "Выпечка",
    image: kruassan,
    description:
      "Круасса́н — небольшое мучное кондитерское изделие, булочка в форме полумесяца из слоёного теста.",
    ingredients: [
      { name: "Слоеное тесто", amount: 250, unit: "г" },
      { name: "Сливочное масло", amount: 50, unit: "г" },
      { name: "Яйцо", amount: 1, unit: "шт" },
    ],
  },
  {
    id: 12,
    name: "Домашний пирог",
    price: "150",
    category: "Выпечка",
    image: domashniy_pirog,
    description: "Сладкий пирог с начинкой из фруктов и крема.",
    ingredients: [
      { name: "Слоеное тесто", amount: 200, unit: "г" },
      { name: "Фруктовая начинка", amount: 100, unit: "г" },
      { name: "Крем", amount: 50, unit: "г" },
    ],
  },
  {
    id: 13,
    name: "Яблочный пирог",
    price: "200",
    category: "Выпечка",
    image: applepirog,
    description: "Сладкий пирог с начинкой из яблок.",
    ingredients: [
      { name: "Слоеное тесто", amount: 200, unit: "г" },
      { name: "Яблоки", amount: 100, unit: "г" },
      { name: "Сахар", amount: 50, unit: "г" },
    ],
  },
  {
    id: 14,
    name: "Мохито",
    price: "299",
    category: "Коктейли",
    image: mohito,
    description: "Освежающий коктейль с мятой, лаймом и ромом.",
    ingredients: [
      { name: "Ром", amount: 50, unit: "мл" },
      { name: "Сахарный сироп", amount: 30, unit: "мл" },
      { name: "Лайм", amount: 1, unit: "шт" },
      { name: "Мята", amount: 10, unit: "г" },
      { name: "Содовая", amount: 100, unit: "мл" },
    ],
  },
  {
    id: 15,
    name: "Багровый закат",
    price: "300",
    category: "Коктейли",
    image: bagrovyi_zakat,
    description: "Коктейль с гранатовым соком и водкой.",
    ingredients: [
      { name: "Водка", amount: 50, unit: "мл" },
      { name: "Гранатовый сок", amount: 100, unit: "мл" },
      { name: "Сахарный сироп", amount: 30, unit: "мл" },
      { name: "Лед", amount: 100, unit: "г" },
    ],
  },
  {
    id: 16,
    name: "Пиво с вином",
    price: "199",
    category: "Коктейли",
    image: beer,
    description: "Пивной напиток в сочетании с вином.",
    ingredients: [
      { name: "Пиво", amount: 100, unit: "мл" },
      { name: "Вино", amount: 50, unit: "мл" },
    ],
  },
  {
    id: 17,
    name: "Джин Тоник",
    price: "350",
    category: "Коктейли",
    image: gintonik,
    description:
      "Джин-тоник — коктейль, содержащий джин и тоник, с добавлением лайма или лимона и льда.",
    ingredients: [
      { name: "Джин", amount: 50, unit: "мл" },
      { name: "Тоник", amount: 150, unit: "мл" },
      { name: "Лайм или лимон", amount: 1, unit: "шт" },
      { name: "Лед", amount: 100, unit: "г" },
    ],
  },
  {
    id: 18,
    name: "Зеленый чай",
    price: "89",
    category: "Чай",
    image: greentea,
    description: "Ароматный и освежающий зеленый чай, богатый антиоксидантами.",
    ingredients: [
      { name: "Зеленый чай", amount: 2, unit: "г" },
      { name: "Горячая вода", amount: 250, unit: "мл" },
    ],
  },
  {
    id: 19,
    name: "Черный чай",
    price: "99",
    category: "Чай",
    image: blacktea,
    description: "Крепкий и бодрящий черный чай с насыщенным вкусом.",
    ingredients: [
      { name: "Черный чай", amount: 2, unit: "г" },
      { name: "Горячая вода", amount: 250, unit: "мл" },
    ],
  },
  {
    id: 20,
    name: "Чай с молоком",
    price: "100",
    category: "Чай",
    image: teawithmilk,
    description: "Чай с добавлением молока.",
    ingredients: [
      { name: "Черный чай", amount: 2, unit: "г" },
      { name: "Горячая вода", amount: 200, unit: "мл" },
      { name: "Молоко", amount: 50, unit: "мл" },
    ],
  },
];

export const initialCategories = [
  { id: 1, name: "Кофе", image: "" },
  { id: 2, name: "Десерты", image: "" },
  { id: 3, name: "Выпечка", image: "" },
  { id: 4, name: "Коктейли", image: "" },
  { id: 5, name: "Чай", image: "" },
];

// Branches

export const initialBranches = [
  {
    id: 1,
    name: "Neocafe Боконбаева",
    address: "Жоомарта Боконбаева, 132",
    phone: "0550123456",
    link: "https://go.2gis.com/gko9u",
    image: "",
    workingHours: {
      Понедельник: { enabled: true, from: "08:00", to: "22:00" },
      Вторник: { enabled: true, from: "08:00", to: "22:00" },
      Среда: { enabled: true, from: "08:00", to: "22:00" },
      Четверг: { enabled: false, from: "08:00", to: "22:00" },
      Пятница: { enabled: false, from: "08:00", to: "22:00" },
      Суббота: { enabled: true, from: "10:00", to: "20:00" },
      Воскресенье: { enabled: true, from: "10:00", to: "20:00" },
    },
  },
  {
    id: 2,
    name: "Neocafe Филармония",
    address: "Табышалиева, 72/1",
    phone: "0555234567",
    link: "https://go.2gis.com/ifh0u",
    image: "",
    workingHours: {
      Понедельник: { enabled: false, from: "09:00", to: "21:00" },
      Вторник: { enabled: false, from: "09:00", to: "21:00" },
      Среда: { enabled: true, from: "09:00", to: "21:00" },
      Четверг: { enabled: true, from: "09:00", to: "21:00" },
      Пятница: { enabled: true, from: "09:00", to: "21:00" },
      Суббота: { enabled: false, from: "11:00", to: "19:00" },
      Воскресенье: { enabled: false, from: "11:00", to: "19:00" },
    },
  },
  {
    id: 3,
    name: "Neocafe Азия Молл",
    address: "Проспект Чынгыза Айтматова, 3",
    phone: "0555123456",
    link: "https://go.2gis.com/nepel",
    image: "",
    workingHours: {
      Понедельник: { enabled: true, from: "09:00", to: "23:00" },
      Вторник: { enabled: true, from: "09:00", to: "23:00" },
      Среда: { enabled: false },
      Четверг: { enabled: true, from: "10:00", to: "22:00" },
      Пятница: { enabled: false },
      Суббота: { enabled: true, from: "09:00", to: "24:00" },
      Воскресенье: { enabled: true, from: "09:00", to: "24:00" },
    },
  },
  {
    id: 4,
    name: "Neocafe Дзержинка",
    address: "Бульвар Эркиндик, 35",
    phone: "0555223456",
    link: "https://go.2gis.com/ffl7x",
    image: "",
    workingHours: {
      Понедельник: { enabled: true, from: "08:00", to: "22:00" },
      Вторник: { enabled: false },
      Среда: { enabled: true, from: "08:00", to: "22:00" },
      Четверг: { enabled: true, from: "08:00", to: "22:00" },
      Пятница: { enabled: true, from: "08:00", to: "22:00" },
      Суббота: { enabled: false },
      Воскресенье: { enabled: true, from: "10:00", to: "20:00" },
    },
  },
  {
    id: 5,
    name: "Neocafe Московская",
    address: "Московская, 73",
    phone: "0555323456",
    link: "https://go.2gis.com/6ltsv",
    image: "",
    workingHours: {
      Понедельник: { enabled: true, from: "09:00", to: "21:00" },
      Вторник: { enabled: true, from: "09:00", to: "21:00" },
      Среда: { enabled: true, from: "09:00", to: "21:00" },
      Четверг: { enabled: true, from: "09:00", to: "21:00" },
      Пятница: { enabled: true, from: "09:00", to: "21:00" },
      Суббота: { enabled: true, from: "10:00", to: "22:00" },
      Воскресенье: { enabled: false },
    },
  },
];

// Stock Items

export const initialStockItems = [
  {
    id: 1,
    name: "Сахар",
    amount: 45,
    unit: "кг",
    limit: 10,
    arrival_date: "2024-04-10",
    category: "raw_materials",
    is_running_out: false,
    stockId: 2,
  },
  {
    id: 2,
    name: "Кофе зерновой",
    amount: 7,
    unit: "кг",
    limit: 10,
    arrival_date: "2024-03-20",
    category: "raw_materials",
    is_running_out: true,
    stockId: 1,
  },
  {
    id: 3,
    name: "Чизкейк",
    amount: 8,
    unit: "шт",
    limit: 4,
    arrival_date: "2024-04-01",
    category: "ready_products",
    is_running_out: false,
    stockId: 1,
  },
  {
    id: 4,
    name: "Молоко",
    amount: 15,
    unit: "л",
    limit: 10,
    arrival_date: "2024-04-15",
    category: "raw_materials",
    is_running_out: false,
    stockId: 3,
  },
  {
    id: 5,
    name: "Соль",
    amount: 5,
    unit: "кг",
    limit: 3,
    arrival_date: "2024-04-10",
    category: "raw_materials",
    is_running_out: false,
    stockId: 2,
  },
  {
    id: 6,
    name: "Мука",
    amount: 2,
    unit: "кг",
    limit: 5,
    arrival_date: "2024-05-05",
    category: "raw_materials",
    is_running_out: true,
    stockId: 1,
  },
  {
    id: 7,
    name: "Карамель",
    amount: 1,
    unit: "кг",
    limit: 2,
    arrival_date: "2024-05-10",
    category: "raw_materials",
    is_running_out: true,
    stockId: 4,
  },
  {
    id: 8,
    name: "Торт Наполеон",
    amount: 6,
    unit: "шт",
    limit: 4,
    arrival_date: "2024-04-22",
    category: "ready_products",
    is_running_out: false,
    stockId: 5,
  },
  {
    id: 9,
    name: "Эклеры",
    amount: 3,
    unit: "шт",
    limit: 5,
    arrival_date: "2024-05-01",
    category: "ready_products",
    is_running_out: true,
    stockId: 1,
  },
  {
    id: 10,
    name: "Клубника",
    amount: 1,
    unit: "кг",
    limit: 2,
    arrival_date: "2024-05-03",
    category: "raw_materials",
    is_running_out: true,
    stockId: 3,
  },
  {
    id: 11,
    name: "Сливки",
    amount: 4,
    unit: "л",
    limit: 5,
    arrival_date: "2024-04-25",
    category: "raw_materials",
    is_running_out: true,
    stockId: 2,
  },
  {
    id: 12,
    name: "Миндаль",
    amount: 3,
    unit: "кг",
    limit: 2,
    arrival_date: "2024-04-30",
    category: "raw_materials",
    is_running_out: false,
    stockId: 4,
  },
  {
    id: 13,
    name: "Брауни",
    amount: 7,
    unit: "шт",
    limit: 3,
    arrival_date: "2024-05-05",
    category: "ready_products",
    is_running_out: false,
    stockId: 1,
  },
  {
    id: 14,
    name: "Мед",
    amount: 10,
    unit: "кг",
    limit: 8,
    arrival_date: "2024-04-12",
    category: "raw_materials",
    is_running_out: false,
    stockId: 5,
  },
  {
    id: 15,
    name: "Черный чай",
    amount: 20,
    unit: "кг",
    limit: 15,
    arrival_date: "2024-04-10",
    category: "raw_materials",
    is_running_out: false,
    stockId: 2,
  },
  {
    id: 16,
    name: "Капучино",
    amount: 5,
    unit: "шт",
    limit: 4,
    arrival_date: "2024-04-15",
    category: "ready_products",
    is_running_out: false,
    stockId: 1,
  },
  {
    id: 17,
    name: "Чай зеленый",
    amount: 8,
    unit: "кг",
    limit: 10,
    arrival_date: "2024-04-20",
    category: "raw_materials",
    is_running_out: true,
    stockId: 3,
  },
  {
    id: 18,
    name: "Сироп карамельный",
    amount: 5,
    unit: "л",
    limit: 6,
    arrival_date: "2024-05-01",
    category: "raw_materials",
    is_running_out: true,
    stockId: 4,
  },
  {
    id: 19,
    name: "Бисквит",
    amount: 2,
    unit: "шт",
    limit: 3,
    arrival_date: "2024-05-03",
    category: "ready_products",
    is_running_out: true,
    stockId: 5,
  },
  {
    id: 20,
    name: "Макаронс клубничный",
    amount: 15,
    unit: "шт",
    limit: 10,
    arrival_date: "2024-04-25",
    category: "ready_products",
    is_running_out: false,
    stockId: 2,
  },
  {
    id: 21,
    name: "Мята",
    amount: 1,
    unit: "кг",
    limit: 2,
    arrival_date: "2024-05-10",
    category: "raw_materials",
    is_running_out: true,
    stockId: 3,
  },
  {
    id: 22,
    name: "Фисташки",
    amount: 6,
    unit: "кг",
    limit: 4,
    arrival_date: "2024-04-30",
    category: "raw_materials",
    is_running_out: false,
    stockId: 4,
  },
  {
    id: 23,
    name: "Маффин",
    amount: 12,
    unit: "шт",
    limit: 8,
    arrival_date: "2024-05-05",
    category: "ready_products",
    is_running_out: false,
    stockId: 5,
  },
  {
    id: 24,
    name: "Арахис",
    amount: 8,
    unit: "кг",
    limit: 10,
    arrival_date: "2024-04-10",
    category: "raw_materials",
    is_running_out: true,
    stockId: 1,
  },
  {
    id: 25,
    name: "Шоколадный торт",
    amount: 5,
    unit: "шт",
    limit: 3,
    arrival_date: "2024-05-05",
    category: "ready_products",
    is_running_out: false,
    stockId: 2,
  },
  {
    id: 26,
    name: "Ягодный мусс",
    amount: 7,
    unit: "шт",
    limit: 4,
    arrival_date: "2024-04-15",
    category: "ready_products",
    is_running_out: false,
    stockId: 3,
  },
  {
    id: 27,
    name: "Крем-брюле",
    amount: 6,
    unit: "шт",
    limit: 5,
    arrival_date: "2024-04-20",
    category: "ready_products",
    is_running_out: false,
    stockId: 4,
  },
  {
    id: 28,
    name: "Круассан",
    amount: 8,
    unit: "шт",
    limit: 6,
    arrival_date: "2024-05-10",
    category: "ready_products",
    is_running_out: false,
    stockId: 2,
  },
  {
    id: 29,
    name: "Эклеры",
    amount: 10,
    unit: "шт",
    limit: 7,
    arrival_date: "2024-04-25",
    category: "ready_products",
    is_running_out: false,
    stockId: 3,
  },
  {
    id: 30,
    name: "Бисквитный торт",
    amount: 3,
    unit: "шт",
    limit: 2,
    arrival_date: "2024-04-30",
    category: "ready_products",
    is_running_out: false,
    stockId: 4,
  },
  {
    id: 31,
    name: "Чизкейк клубничный",
    amount: 12,
    unit: "шт",
    limit: 8,
    arrival_date: "2024-05-03",
    category: "ready_products",
    is_running_out: false,
    stockId: 2,
  },
  {
    id: 32,
    name: "Маффины",
    amount: 4,
    unit: "шт",
    limit: 3,
    arrival_date: "2024-05-05",
    category: "ready_products",
    is_running_out: false,
    stockId: 3,
  },
  {
    id: 33,
    name: "Пирог с вишней",
    amount: 2,
    unit: "шт",
    limit: 1,
    arrival_date: "2024-04-22",
    category: "ready_products",
    is_running_out: true,
    stockId: 4,
  },
  {
    id: 34,
    name: "Тирамису",
    amount: 9,
    unit: "шт",
    limit: 6,
    arrival_date: "2024-05-05",
    category: "ready_products",
    is_running_out: false,
    stockId: 2,
  },
  {
    id: 35,
    name: "Макаронc шоколадный",
    amount: 20,
    unit: "шт",
    limit: 15,
    arrival_date: "2024-05-01",
    category: "ready_products",
    is_running_out: false,
    stockId: 3,
  },
  {
    id: 36,
    name: "Печенье",
    amount: 5,
    unit: "шт",
    limit: 4,
    arrival_date: "2024-04-10",
    category: "ready_products",
    is_running_out: false,
    stockId: 4,
  },
  {
    id: 37,
    name: "Кекс шоколадный",
    amount: 7,
    unit: "шт",
    limit: 5,
    arrival_date: "2024-04-15",
    category: "ready_products",
    is_running_out: false,
    stockId: 2,
  },
  {
    id: 38,
    name: "Тарталетки",
    amount: 6,
    unit: "шт",
    limit: 4,
    arrival_date: "2024-04-30",
    category: "ready_products",
    is_running_out: false,
    stockId: 3,
  },
  {
    id: 39,
    name: "Чизкейк шоколадный",
    amount: 5,
    unit: "шт",
    limit: 3,
    arrival_date: "2024-05-10",
    category: "ready_products",
    is_running_out: false,
    stockId: 4,
  },
  {
    id: 40,
    name: "Фруктовый торт",
    amount: 8,
    unit: "шт",
    limit: 6,
    arrival_date: "2024-04-25",
    category: "ready_products",
    is_running_out: false,
    stockId: 2,
  },
  {
    id: 41,
    name: "Сэндвич с ветчиной",
    amount: 6,
    unit: "шт",
    limit: 5,
    arrival_date: "2024-04-22",
    category: "ready_products",
    is_running_out: false,
    stockId: 4,
  },
  {
    id: 42,
    name: "Мука",
    amount: 10,
    unit: "кг",
    limit: 5,
    arrival_date: "2024-04-12",
    category: "raw_materials",
    is_running_out: false,
    stockId: 5,
  },
  {
    id: 43,
    name: "Сахар",
    amount: 15,
    unit: "кг",
    limit: 10,
    arrival_date: "2024-04-20",
    category: "raw_materials",
    is_running_out: false,
    stockId: 5,
  },
  {
    id: 44,
    name: "Сливочное масло",
    amount: 8,
    unit: "кг",
    limit: 5,
    arrival_date: "2024-04-25",
    category: "raw_materials",
    is_running_out: false,
    stockId: 5,
  },
  {
    id: 45,
    name: "Какао",
    amount: 2,
    unit: "кг",
    limit: 3,
    arrival_date: "2024-05-01",
    category: "raw_materials",
    is_running_out: true,
    stockId: 5,
  },
  {
    id: 46,
    name: "Шоколадная глазурь",
    amount: 4,
    unit: "кг",
    limit: 2,
    arrival_date: "2024-05-05",
    category: "raw_materials",
    is_running_out: false,
    stockId: 5,
  },
  {
    id: 47,
    name: "Фрукты ассорти",
    amount: 5,
    unit: "кг",
    limit: 3,
    arrival_date: "2024-04-15",
    category: "raw_materials",
    is_running_out: false,
    stockId: 5,
  },
  {
    id: 48,
    name: "Орехи грецкие",
    amount: 3,
    unit: "кг",
    limit: 2,
    arrival_date: "2024-04-30",
    category: "raw_materials",
    is_running_out: false,
    stockId: 5,
  },
  {
    id: 49,
    name: "Карамельный сироп",
    amount: 6,
    unit: "л",
    limit: 4,
    arrival_date: "2024-05-10",
    category: "raw_materials",
    is_running_out: false,
    stockId: 5,
  },
  {
    id: 50,
    name: "Молоко сгущенное",
    amount: 5,
    unit: "кг",
    limit: 3,
    arrival_date: "2024-04-25",
    category: "raw_materials",
    is_running_out: false,
    stockId: 5,
  },
  {
    id: 51,
    name: "Яйца",
    amount: 20,
    unit: "шт",
    limit: 15,
    arrival_date: "2024-05-01",
    category: "raw_materials",
    is_running_out: false,
    stockId: 5,
  },
  {
    id: 52,
    name: "Пирожное картошка",
    amount: 10,
    unit: "шт",
    limit: 6,
    arrival_date: "2024-04-12",
    category: "ready_products",
    is_running_out: false,
    stockId: 5,
  },
  {
    id: 53,
    name: "Тарталетки с фруктами",
    amount: 8,
    unit: "шт",
    limit: 5,
    arrival_date: "2024-04-15",
    category: "ready_products",
    is_running_out: false,
    stockId: 5,
  },
  {
    id: 54,
    name: "Кексы с изюмом",
    amount: 12,
    unit: "шт",
    limit: 7,
    arrival_date: "2024-04-20",
    category: "ready_products",
    is_running_out: false,
    stockId: 5,
  },
  {
    id: 55,
    name: "Эклеры с кремом",
    amount: 9,
    unit: "шт",
    limit: 6,
    arrival_date: "2024-04-25",
    category: "ready_products",
    is_running_out: false,
    stockId: 5,
  },
  {
    id: 56,
    name: "Тирамису",
    amount: 7,
    unit: "шт",
    limit: 5,
    arrival_date: "2024-05-01",
    category: "ready_products",
    is_running_out: false,
    stockId: 5,
  },
  {
    id: 57,
    name: "Чизкейк ванильный",
    amount: 6,
    unit: "шт",
    limit: 4,
    arrival_date: "2024-05-05",
    category: "ready_products",
    is_running_out: false,
    stockId: 5,
  },
  {
    id: 58,
    name: "Мусс манго",
    amount: 11,
    unit: "шт",
    limit: 8,
    arrival_date: "2024-05-10",
    category: "ready_products",
    is_running_out: false,
    stockId: 5,
  },
  {
    id: 59,
    name: "Шоколадное пирожное",
    amount: 5,
    unit: "шт",
    limit: 3,
    arrival_date: "2024-04-30",
    category: "ready_products",
    is_running_out: false,
    stockId: 5,
  },
];

// Employees

export const initialEmployees = [
  {
    id: 1,
    login: "aidai_j",
    password: "securepassword123",
    first_name: "Айдай",
    last_name: "Жапарова",
    position: "waiter",
    dob: "1990-01-01",
    phone: "+996500111222",
    branch: 1,
    workingHours: {
      Понедельник: { enabled: true, from: "09:00", to: "17:00" },
      Вторник: { enabled: true, from: "09:00", to: "17:00" },
      Среда: { enabled: true, from: "09:00", to: "17:00" },
      Четверг: { enabled: false, from: "11:00", to: "22:00" },
      Пятница: { enabled: false, from: "11:00", to: "22:00" },
      Суббота: { enabled: true, from: "10:00", to: "14:00" },
      Воскресенье: { enabled: false, from: "08:00", to: "17:00" },
    },
  },
  {
    id: 2,
    login: "daniyar_b",
    password: "passwordsecure456",
    first_name: "Данияр",
    last_name: "Болотбеков",
    position: "barista",
    dob: "1985-05-05",
    phone: "+996500333444",
    branch: 2,
    workingHours: {
      Понедельник: { enabled: true, from: "10:00", to: "18:00" },
      Вторник: { enabled: true, from: "10:00", to: "18:00" },
      Среда: { enabled: true, from: "10:00", to: "18:00" },
      Четверг: { enabled: true, from: "10:00", to: "18:00" },
      Пятница: { enabled: true, from: "10:00", to: "18:00" },
      Суббота: { enabled: false, from: "08:00", to: "17:00" },
      Воскресенье: { enabled: false, from: "08:00", to: "17:00" },
    },
  },
  {
    id: 3,
    login: "aijamal_k",
    password: "securepassword123",
    first_name: "Айжамал",
    last_name: "Касымова",
    position: "waiter",
    dob: "1990-01-01",
    phone: "+996500111222",
    branch: 1,
    workingHours: {
      Понедельник: { enabled: true, from: "09:00", to: "17:00" },
      Вторник: { enabled: true, from: "09:00", to: "17:00" },
      Среда: { enabled: true, from: "09:00", to: "17:00" },
      Четверг: { enabled: false, from: "11:00", to: "22:00" },
      Пятница: { enabled: false, from: "11:00", to: "22:00" },
      Суббота: { enabled: true, from: "10:00", to: "14:00" },
      Воскресенье: { enabled: false, from: "08:00", to: "17:00" },
    },
  },
  {
    id: 4,
    login: "daniyar_b",
    password: "passwordsecure456",
    first_name: "Темирлан",
    last_name: "Аманов",
    position: "waiter",
    dob: "1985-05-05",
    phone: "+996500333444",
    branch: 2,
    workingHours: {
      Понедельник: { enabled: true, from: "10:00", to: "18:00" },
      Вторник: { enabled: true, from: "10:00", to: "18:00" },
      Среда: { enabled: true, from: "10:00", to: "18:00" },
      Четверг: { enabled: true, from: "10:00", to: "18:00" },
      Пятница: { enabled: true, from: "10:00", to: "18:00" },
      Суббота: { enabled: false, from: "08:00", to: "17:00" },
      Воскресенье: { enabled: false, from: "08:00", to: "17:00" },
    },
  },
  {
    id: 5,
    login: "begimai_t",
    password: "strongpass789",
    first_name: "Бегимай",
    last_name: "Токтосунова",
    position: "waiter",
    dob: "1993-07-15",
    phone: "+996500555666",
    branch: 3,
    workingHours: {
      Понедельник: { enabled: true, from: "08:00", to: "16:00" },
      Вторник: { enabled: true, from: "08:00", to: "16:00" },
      Среда: { enabled: true, from: "08:00", to: "16:00" },
      Четверг: { enabled: true, from: "08:00", to: "16:00" },
      Пятница: { enabled: false, from: "10:00", to: "18:00" },
      Суббота: { enabled: false, from: "10:00", to: "18:00" },
      Воскресенье: { enabled: true, from: "09:00", to: "14:00" },
    },
  },
  {
    id: 6,
    login: "almaz_s",
    password: "mypassword321",
    first_name: "Алмаз",
    last_name: "Сатыбалдиев",
    position: "barista",
    dob: "1988-09-23",
    phone: "+996500777888",
    branch: 4,
    workingHours: {
      Понедельник: { enabled: true, from: "09:00", to: "17:00" },
      Вторник: { enabled: true, from: "09:00", to: "17:00" },
      Среда: { enabled: false, from: "11:00", to: "19:00" },
      Четверг: { enabled: true, from: "09:00", to: "17:00" },
      Пятница: { enabled: true, from: "09:00", to: "17:00" },
      Суббота: { enabled: true, from: "10:00", to: "14:00" },
      Воскресенье: { enabled: false, from: "12:00", to: "18:00" },
    },
  },
  {
    id: 7,
    login: "nurzhan_a",
    password: "securepass654",
    first_name: "Нуржан",
    last_name: "Асанова",
    position: "waiter",
    dob: "1995-02-12",
    phone: "+996500999111",
    branch: 2,
    workingHours: {
      Понедельник: { enabled: false, from: "09:00", to: "17:00" },
      Вторник: { enabled: true, from: "10:00", to: "18:00" },
      Среда: { enabled: true, from: "10:00", to: "18:00" },
      Четверг: { enabled: true, from: "10:00", to: "18:00" },
      Пятница: { enabled: false, from: "11:00", to: "19:00" },
      Суббота: { enabled: true, from: "08:00", to: "14:00" },
      Воскресенье: { enabled: false, from: "09:00", to: "15:00" },
    },
  },
  {
    id: 8,
    login: "gulnara_b",
    password: "safepass987",
    first_name: "Гульнара",
    last_name: "Байзакова",
    position: "barista",
    dob: "1982-11-08",
    phone: "+996500222333",
    branch: 5,
    workingHours: {
      Понедельник: { enabled: true, from: "07:00", to: "15:00" },
      Вторник: { enabled: true, from: "07:00", to: "15:00" },
      Среда: { enabled: true, from: "07:00", to: "15:00" },
      Четверг: { enabled: false, from: "09:00", to: "17:00" },
      Пятница: { enabled: true, from: "07:00", to: "15:00" },
      Суббота: { enabled: false, from: "10:00", to: "18:00" },
      Воскресенье: { enabled: true, from: "08:00", to: "12:00" },
    },
  },
  {
    id: 9,
    login: "bakyt_b",
    password: "passsecure654",
    first_name: "Бакыт",
    last_name: "Бекболотов",
    position: "barista",
    dob: "1994-04-25",
    phone: "+996500444555",
    branch: 1,
    workingHours: {
      Понедельник: { enabled: false, from: "09:00", to: "17:00" },
      Вторник: { enabled: true, from: "10:00", to: "18:00" },
      Среда: { enabled: true, from: "10:00", to: "18:00" },
      Четверг: { enabled: true, from: "10:00", to: "18:00" },
      Пятница: { enabled: true, from: "11:00", to: "19:00" },
      Суббота: { enabled: false, from: "08:00", to: "14:00" },
      Воскресенье: { enabled: true, from: "09:00", to: "15:00" },
    },
  },
  {
    id: 10,
    login: "nurgul_s",
    password: "passwordsafe321",
    first_name: "Нургуль",
    last_name: "Султанова",
    position: "barista",
    dob: "1987-10-30",
    phone: "+996500666777",
    branch: 3,
    workingHours: {
      Понедельник: { enabled: true, from: "08:00", to: "16:00" },
      Вторник: { enabled: false, from: "09:00", to: "17:00" },
      Среда: { enabled: true, from: "08:00", to: "16:00" },
      Четверг: { enabled: true, from: "08:00", to: "16:00" },
      Пятница: { enabled: true, from: "08:00", to: "16:00" },
      Суббота: { enabled: false, from: "10:00", to: "18:00" },
      Воскресенье: { enabled: true, from: "09:00", to: "14:00" },
    },
  },
  {
    id: 11,
    login: "tilek_u",
    password: "mypassword789",
    first_name: "Тилек",
    last_name: "Усенов",
    position: "waiter",
    dob: "1991-03-18",
    phone: "+996500888999",
    branch: 4,
    workingHours: {
      Понедельник: { enabled: false, from: "07:00", to: "15:00" },
      Вторник: { enabled: true, from: "08:00", to: "16:00" },
      Среда: { enabled: true, from: "08:00", to: "16:00" },
      Четверг: { enabled: true, from: "08:00", to: "16:00" },
      Пятница: { enabled: true, from: "08:00", to: "16:00" },
      Суббота: { enabled: true, from: "09:00", to: "12:00" },
      Воскресенье: { enabled: false, from: "09:00", to: "12:00" },
    },
  },
];
